from __future__ import annotations

from dataclasses import dataclass, asdict
from datetime import datetime


@dataclass(frozen=True, slots=True)
class Signal:
    """A trade signal generated by a strategy."""

    instrument: str
    strategy: str
    side: str  # "long" or "short"
    entry_price: float
    stop: float
    target: float
    rationale: str
    regime_context: str
    timestamp: datetime | None = None
    confidence: float = 0.0
    action: str = "enter"  # "enter" | "exit"

    def to_dict(self) -> dict:
        d = asdict(self)
        if self.timestamp is not None:
            d["timestamp"] = self.timestamp.isoformat()
        return d

    @classmethod
    def from_dict(cls, d: dict) -> Signal:
        data = dict(d)
        if isinstance(data.get("timestamp"), str):
            data["timestamp"] = datetime.fromisoformat(data["timestamp"])
        return cls(**data)
